### ISSUE TITLE
Issues from carpentries lab submission

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/deep-learning-intro#423]
Fix issues mentioned in https://github.com/carpentries-lab/reviews/issues/25#issuecomment-1787189928
```[tasklist]
### Tasks
- [ ] https://github.com/carpentries-incubator/deep-learning-intro/issues/430
- [ ] https://github.com/carpentries-incubator/deep-learning-intro/issues/431
- [ ] https://github.com/carpentries-incubator/deep-learning-intro/issues/439
```

**Comment by svenvanderburg** [comment]
All tasks are finished!
