### ISSUE TITLE
Fix minor comments from Carpentries Lab review

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/deep-learning-intro#449]
Look at https://github.com/carpentries-lab/reviews/issues/25, see if there are any minor comments that we missed and can still improve.
```[tasklist]
### Tasks
- [x] listed browser support is not matched to jupyter browser support notably, Windows' current default browser is a chromium browser and therefore supported (and on general web compatibility, better than safari by a nontrivial margin) this should be updated to include more windows users without having to install
- [x] a glossary of key terms or links out to definitions in an external glossary e.g. Glosario.
```

**Comment by carschno** [comment]
Extracting the specific items from https://github.com/carpentries-lab/reviews/issues/25 that are still open:

- [ ] listed browser support is not matched to [jupyter browser support](https://jupyterlab.readthedocs.io/en/latest/getting_started/accessibility.html#:~:text=Android-,Browsers%20(mobile%20and%20desktop)%3A,-Firefox) notably, Windows' current default browser is a chromium browser and therefore supported (and on general web compatibility, better than safari by a nontrivial margin) this should be updated to include more windows users without having to install
- [ ] all episodes are 55min + episode 3 is over 3 hours long?
- [ ] a glossary of key terms or links out to definitions in an external glossary e.g. [Glosario](https://carpentries.github.io/glosario/).
- [ ] Setup: it says "open a terminal" but that is insufficient information for a Windows user (they have multiple terminals and to launch jupyter only the "anaconda prompt" by default will work; CMD or powershell typically will not)
