### ISSUE TITLE
Replace Anaconda

### ISSUE THREAD

**Issue by carschno** [carpentries-incubator/deep-learning-intro#511]
In the current setup instruction, we link to the Anaconda installation page: https://www.anaconda.com/products/distribution
This currently redirects to https://www.anaconda.com/download which requires providing an email to get to the software.
This forms a privacy-related obstacle. A free/open that approach would be preferable.

# Alternative Options

**Update:** I have implemented a version using pip/env in #513. Given that the installation remains flawless and that it does not require installing additional tools, I find this to be the preferred option.

@colinsauze @psteinb Do you have any opinion on this issue?
I personally prefer Poetry, but also see an advantage in using built-in tooling (venv).
I do not see a reason for still using Conda, but it is difficult to generalize this.
Is there a general discussion about Conda in Carpentries?

## [Miniconda](https://docs.anaconda.com/miniconda/)
Advantages:
- Apart from the Anaconda installation, the installation works in the same way as now
- Does (currently) not require (privacy-related) extra step for downloading

Disadvantages:
- License is the same as for Anaconda (free for non-commercial use)
- Conditions for download and for usage can change in the future

## Pip and [venv](https://docs.python.org/3/library/venv.html)

Advantages:
- Comes with Python, no installation required
- Established practice, probably already known by many learners
- Free and open license

Disadvantages:
- Requires update in the lesson
- Additional cognitive load: requires learners to create an environment and to use it consistently

## [Poetry](https://python-poetry.org/)

Advantages:
- Easy installation
- Good at resolving dependency issues (in isolated environment)
- Free and open license
- Popular and established, might already be known by some learners

Disadvantages:
- Requires update in the lesson
- Cognitive load: requires learners to install and use new tool Poetry
```[tasklist]
### Tasks
- [x] Replace or remove "Installing Python using Anaconda" block
- [x] Adapt "Installing the required packages" block
- [x] Double-check or remove "Python package installation troubleshooting" block
- [x] Check if Jupyter Lab uses the correct environment/Python kernel
```

**Comment by carschno** [comment]
I'm looking into the Pip/Venv version for starters.

**Comment by carschno** [comment]
The pip/venv solution seems very easy, there is no longer a need for additional tools.
I have double-checked every step of the MacOS/Linux solution.
