### ISSUE TITLE
Resolve 2nd round of comments Mike

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/deep-learning-intro#515]
See https://github.com/carpentries-lab/reviews/issues/25#issuecomment-2260090524
```[tasklist]
### Tasks
- [x] Episode 3, Identify inputs and outputs: make outputs explicit
- [x] Episode 3, Choose a pretrained model or start building architecture from scratch: do not use global `X_data`
- [ ] ~~Episode 3, Choose a pretrained model or start building architecture from scratch: avoid redefining `create_nn` in 'reduce overfitting'~~
- [ ] ~~Episode 3, Choose a pretrained model or start building architecture from scratch: avoid redefining `create_nn` in 'BatchNorm' section~~
- [x] Episode 3, Train the model: `batch_size` not introduced for the first time
- [x] Episode 3, Refine the model: fix phrasing
- [x] Episode 3, Refine the model: refine explanation of early stopping
- [x] Episode 4, Dropout: typo in layertowards
- [x] Episode 4, Dropout: we only add one dropout in `creete_nn_with_dropout()`
- [x] Episode 4, Dropout: number of Dropout laysers inconsistent
- [ ] (optional) Episode 4: move `pip install keras_tuner` to setup instructions
- [x] Episode 5: identify inputs and outputs: mention inputs and output
- [x] Episode 5, Choose a pre-trained model or start building architecture from scratch: the inputs are defined in section 4, and the upscale layer is a "kind of" data prep conceptually
- [x] Episode 5, Choose a pre-trained model or start building architecture from scratch: clarify that steps 2+3 depend on pretrained model
- [x] Outlook: bump instructor note to above paragraph it references
```
